# Armour item templates

[item]
name=Leather Armor
symbol=[
type=ARMOR_CHEST
categories=equipable,armour
stackable=0
quantity=1
power=2
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Leather Cap
symbol=[
type=ARMOR_HEAD
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Leather Bracers
symbol=[
type=ARMOR_ARMS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Padded Jack
symbol=[
type=ARMOR_CHEST
categories=equipable,armour
stackable=0
quantity=1
power=3
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Leather Gloves
symbol=[
type=ARMOR_HANDS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Leather Boots
symbol=[
type=ARMOR_BOOTS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Mail Coif
symbol=[
type=ARMOR_HEAD
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Mail Standard
symbol=[
type=ARMOR_NECK
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Mail Mantle
symbol=[
type=ARMOR_SHOULDERS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Mail Hauberk
symbol=[
type=ARMOR_CHEST
categories=equipable,armour
stackable=0
quantity=1
power=3
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Mail Skirt
symbol=[
type=ARMOR_WAIST
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Mail Sleeves
symbol=[
type=ARMOR_ARMS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Mail Mittens
symbol=[
type=ARMOR_HANDS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Mail Chausses
symbol=[
type=ARMOR_LEGS
categories=equipable,armour
stackable=0
quantity=1
power=2
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Mail Boots
symbol=[
type=ARMOR_BOOTS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Plate Helm
symbol=[
type=ARMOR_HEAD
categories=equipable,armour
stackable=0
quantity=1
power=2
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Steel Gorget
symbol=[
type=ARMOR_NECK
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Plate Pauldrons
symbol=[
type=ARMOR_SHOULDERS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Breastplate
symbol=[
type=ARMOR_CHEST
categories=equipable,armour
stackable=0
quantity=1
power=4
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Plate Fauld
symbol=[
type=ARMOR_WAIST
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Plate Vambraces
symbol=[
type=ARMOR_ARMS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Steel Gauntlets
symbol=[
type=ARMOR_HANDS
categories=equipable,armour
stackable=0
quantity=1
power=1
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Plate Cuisses
symbol=[
type=ARMOR_LEGS
categories=equipable,armour
stackable=0
quantity=1
power=3
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE

[item]
name=Sabatons
symbol=[
type=ARMOR_BOOTS
categories=equipable,armour
stackable=0
quantity=1
power=2
weapon_skill=NONE
accuracy_bonus=0
crit_bonus=0
parry_bonus=0
can_parry=0
damage_types=NONE
attack_modes=NONE
