# Material item templates

[item]
name=Iron Ore
symbol=*
type=KEY
categories=material,metal,unrefined
stackable=1
quantity=3
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=UNREFINED

[item]
name=Copper Ore
symbol=*
type=KEY
categories=material,metal,unrefined
stackable=1
quantity=3
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=UNREFINED

[item]
name=Tin Ore
symbol=*
type=KEY
categories=material,metal,unrefined
stackable=1
quantity=3
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=UNREFINED

[item]
name=Lead Ore
symbol=*
type=KEY
categories=material,metal,unrefined
stackable=1
quantity=3
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=UNREFINED

[item]
name=Zinc Ore
symbol=*
type=KEY
categories=material,metal,unrefined
stackable=1
quantity=3
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=UNREFINED

[item]
name=Iron Ingot
symbol==
type=KEY
categories=material,metal,refined
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=REFINED

[item]
name=Copper Ingot
symbol==
type=KEY
categories=material,metal,refined
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=REFINED

[item]
name=Tin Ingot
symbol==
type=KEY
categories=material,metal,refined
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=REFINED

[item]
name=Lead Ingot
symbol==
type=KEY
categories=material,metal,refined
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=REFINED

[item]
name=Zinc Ingot
symbol==
type=KEY
categories=material,metal,refined
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=METAL
material_state=REFINED

[item]
name=Wood Log
symbol=|
type=KEY
categories=material,wood,unrefined
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=WOOD
material_state=UNREFINED

[item]
name=Log
symbol=|
type=KEY
categories=material,wood,unrefined
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=WOOD
material_state=UNREFINED

[item]
name=Oak Log
symbol=|
type=KEY
categories=material,wood,unrefined,oak
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=WOOD
material_state=UNREFINED

[item]
name=Spruce Log
symbol=|
type=KEY
categories=material,wood,unrefined,spruce
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=WOOD
material_state=UNREFINED

[item]
name=Pine Log
symbol=|
type=KEY
categories=material,wood,unrefined,pine
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=WOOD
material_state=UNREFINED

[item]
name=Birch Log
symbol=|
type=KEY
categories=material,wood,unrefined,birch
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=WOOD
material_state=UNREFINED

[item]
name=Yew Log
symbol=|
type=KEY
categories=material,wood,unrefined,yew
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=WOOD
material_state=UNREFINED

[item]
name=Maple Log
symbol=|
type=KEY
categories=material,wood,unrefined,maple
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=WOOD
material_state=UNREFINED

[item]
name=Wood Plank
symbol==
type=KEY
categories=material,wood,refined
stackable=1
quantity=4
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Wood Bolt
symbol==
type=KEY
categories=material,wood,refined
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Oak Bolt
symbol==
type=KEY
categories=material,wood,refined,oak
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Spruce Bolt
symbol==
type=KEY
categories=material,wood,refined,spruce
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Pine Bolt
symbol==
type=KEY
categories=material,wood,refined,pine
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Birch Bolt
symbol==
type=KEY
categories=material,wood,refined,birch
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Yew Bolt
symbol==
type=KEY
categories=material,wood,refined,yew
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Maple Bolt
symbol==
type=KEY
categories=material,wood,refined,maple
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Wood Billet
symbol==
type=KEY
categories=material,wood,refined
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Oak Billet
symbol==
type=KEY
categories=material,wood,refined,oak
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Spruce Billet
symbol==
type=KEY
categories=material,wood,refined,spruce
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Pine Billet
symbol==
type=KEY
categories=material,wood,refined,pine
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Birch Billet
symbol==
type=KEY
categories=material,wood,refined,birch
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Yew Billet
symbol==
type=KEY
categories=material,wood,refined,yew
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Maple Billet
symbol==
type=KEY
categories=material,wood,refined,maple
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Firewood
symbol=|
type=KEY
categories=material,wood,refined,fuel
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Oak Firewood
symbol=|
type=KEY
categories=material,wood,refined,fuel,oak
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Spruce Firewood
symbol=|
type=KEY
categories=material,wood,refined,fuel,spruce
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Pine Firewood
symbol=|
type=KEY
categories=material,wood,refined,fuel,pine
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Birch Firewood
symbol=|
type=KEY
categories=material,wood,refined,fuel,birch
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Yew Firewood
symbol=|
type=KEY
categories=material,wood,refined,fuel,yew
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Maple Firewood
symbol=|
type=KEY
categories=material,wood,refined,fuel,maple
stackable=1
quantity=2
stack_max=99
power=0
is_material=1
material_type=WOOD
material_state=REFINED

[item]
name=Rough Quartz
symbol=*
type=KEY
categories=material,gemstone,unrefined
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=GEMSTONE
material_state=UNREFINED

[item]
name=Cured Hide
symbol=~
type=KEY
categories=material,leather,refined
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=LEATHER
material_state=REFINED

[item]
name=Cloth Bolt
symbol=~
type=KEY
categories=material,cloth,refined
stackable=1
quantity=2
stack_max=50
power=0
is_material=1
material_type=CLOTH
material_state=REFINED
